# MC:
# compatible con todas las versiones de nrf52840 (xiao):
# - seeeduino_xiao_ble (probado)

CONFIG_PROSPECTOR_MODE_SCANNER=y
CONFIG_PROSPECTOR_TOUCH_ENABLED=n

CONFIG_PROSPECTOR_MULTI_KEYBOARD=y
CONFIG_PROSPECTOR_MAX_KEYBOARDS=3

CONFIG_BT_OBSERVER=y

### DONGLE MODE
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

### DISPLAY DONGLE OPTIONS
CONFIG_ZMK_DISPLAY=y
CONFIG_DISPLAY=y

CONFIG_LVGL=y
CONFIG_LV_USE_SLIDER=y
CONFIG_LV_FONT_MONTSERRAT_20=y

CONFIG_PROSPECTOR_MAX_LAYERS=7
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n

CONFIG_PROSPECTOR_SCANNER_MAIN_LOOP_INTERVAL_MS=120
CONFIG_PROSPECTOR_SCANNER_TIMEOUT_MS=480000

CONFIG_ZMK_SPLIT=n

CONFIG_BT_LOG_LEVEL_WRN=y
CONFIG_LOG_DEFAULT_LEVEL=4

### POWER OPTIONS
# La unidad del intervalo del informe de energía de la batería es segundos
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60

### DEBUG OPTIONS
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

### PROSPECTOR
CONFIG_PROSPECTOR_ROTATE_DISPLAY_180=y
